"""update transcript schema

Revision ID: 306d50b8ed3f
Revises: 00a52832d05d
Create Date: 2026-07-17 23:34:13.283087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306d50b8ed3f'
down_revision: Union[str, Sequence[str], None] = '00a52832d05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('start_time', sa.Float(), nullable=False))
    op.add_column('transcripts', sa.Column('end_time', sa.Float(), nullable=False))
    op.drop_column('transcripts', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('timestamp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('transcripts', 'end_time')
    op.drop_column('transcripts', 'start_time')
    # ### end Alembic commands ###
